INCLUDES = -I./include
FLAGS = -g
LIBPATH = -L./lib
LIBS = -lmingw32 -lSDL2main -lSDL2
OUTPUT = ./bin/main
SOURCES = ./src/main.c

all:
	gcc $(FLAGS) $(INCLUDES) $(SOURCES) $(LIBPATH) $(LIBS) -o $(OUTPUT)